### ISSUE TITLE
Insufficient earbuds device details

### ISSUE THREAD

**Issue by amMistic** [aryanvgithub/Smart-Mask-UbiComp2022#1]
Can you please share the device details, like which earbuds(boat, noise with full model name) you used and is it able to transfer the audio data wirelessly to the laptop or smartphone.

**Comment by amMistic** [comment]
i mean breathing audio data

**Comment by aryanv30** [comment]
It is mentioned in the "Audio" section of the repo. Please refer to this [link](https://github.com/aryanvgithub/Smart-Mask-UbiComp2022/blob/main/Audio/Wireless_Bud(Realme%20Buds%20Q2%20Neo).jpg).
